"""add order_item_groups and extend order_items

Revision ID: 09bafcc16a67
Revises: 3c0f05a311a5
Create Date: 2026-03-27 04:46:36.984739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '09bafcc16a67'
down_revision: Union[str, None] = '3c0f05a311a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order_item_groups',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_id', 'name', name='uq_group_order_name')
    )
    op.create_index('ix_group_order_position', 'order_item_groups', ['order_id', 'position'], unique=False)
    op.create_index(op.f('ix_order_item_groups_order_id'), 'order_item_groups', ['order_id'], unique=False)
    op.add_column('order_items', sa.Column('group_id', sa.String(length=36), nullable=True))
    op.add_column('order_items', sa.Column('quantity', sa.Integer(), server_default='1', nullable=False))
    op.add_column('order_items', sa.Column('instance_parameters', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.create_index(op.f('ix_order_items_group_id'), 'order_items', ['group_id'], unique=False)
    op.create_foreign_key(None, 'order_items', 'order_item_groups', ['group_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.drop_index(op.f('ix_order_items_group_id'), table_name='order_items')
    op.drop_column('order_items', 'instance_parameters')
    op.drop_column('order_items', 'quantity')
    op.drop_column('order_items', 'group_id')
    op.drop_index(op.f('ix_order_item_groups_order_id'), table_name='order_item_groups')
    op.drop_index('ix_group_order_position', table_name='order_item_groups')
    op.drop_table('order_item_groups')
    # ### end Alembic commands ###
