"""add credential_links table

Revision ID: 3c0f05a311a5
Revises: 5e6a46a6282d
Create Date: 2026-03-27 01:46:27.023523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3c0f05a311a5'
down_revision: Union[str, None] = '5e6a46a6282d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('credential_links',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('credentials', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accessed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_consumed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_credential_links_order_item_id'), 'credential_links', ['order_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_credential_links_order_item_id'), table_name='credential_links')
    op.drop_table('credential_links')
    # ### end Alembic commands ###
