"""add context rules and tenant assignments

Revision ID: 95048f8ace5c
Revises: e67e9d598d79
Create Date: 2026-03-27 00:34:56.257473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95048f8ace5c'
down_revision: Union[str, None] = 'e67e9d598d79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_rules',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_slug', sa.String(length=64), nullable=False),
    sa.Column('rule_type', sa.String(length=10), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availability_rules_template_slug'), 'availability_rules', ['template_slug'], unique=False)
    op.create_table('context_restrictions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('template_slug', sa.String(length=64), nullable=True),
    sa.Column('parameter_key', sa.String(length=64), nullable=False),
    sa.Column('restriction_type', sa.String(length=20), nullable=False),
    sa.Column('conditions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('effect', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_tenant_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=100), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_user_tenant')
    )
    op.create_index(op.f('ix_user_tenant_assignments_user_id'), 'user_tenant_assignments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tenant_assignments_user_id'), table_name='user_tenant_assignments')
    op.drop_table('user_tenant_assignments')
    op.drop_table('context_restrictions')
    op.drop_index(op.f('ix_availability_rules_template_slug'), table_name='availability_rules')
    op.drop_table('availability_rules')
    # ### end Alembic commands ###
