"""add service_templates table

Revision ID: ceb945db2538
Revises: 
Create Date: 2026-03-26 23:24:20.371263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ceb945db2538'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('icon_identifier', sa.String(length=100), nullable=True),
    sa.Column('tofu_module_source', sa.String(length=500), nullable=False),
    sa.Column('parameters', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cross_parameter_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deprecated_by', sa.String(length=36), nullable=True),
    sa.Column('estimated_cost_eur_per_month', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('approval_always_required', sa.Boolean(), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug', 'version', name='uq_template_slug_version')
    )
    op.create_index(op.f('ix_service_templates_category'), 'service_templates', ['category'], unique=False)
    op.create_index(op.f('ix_service_templates_slug'), 'service_templates', ['slug'], unique=False)
    op.create_index(op.f('ix_service_templates_status'), 'service_templates', ['status'], unique=False)
    op.create_index(op.f('ix_service_templates_type'), 'service_templates', ['type'], unique=False)
    op.create_index('ix_template_slug_status', 'service_templates', ['slug', 'status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_template_slug_status', table_name='service_templates')
    op.drop_index(op.f('ix_service_templates_type'), table_name='service_templates')
    op.drop_index(op.f('ix_service_templates_status'), table_name='service_templates')
    op.drop_index(op.f('ix_service_templates_slug'), table_name='service_templates')
    op.drop_index(op.f('ix_service_templates_category'), table_name='service_templates')
    op.drop_table('service_templates')
    # ### end Alembic commands ###
